# Generated by Django 4.0.2 on 2022-03-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        ('accounts', '0003_rename_confirmation_code_confirmationcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tracker.site'),
        ),
    ]
