# Generated by Django 4.0.2 on 2022-03-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_invitation_guest_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='guest',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Guest Email'),
        ),
    ]
