# Generated by Django 4.0.2 on 2022-03-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_invitation_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'project Manager'), ('3', 'Developer')], default='3', max_length=1),
        ),
    ]
