# Generated by Django 4.0.2 on 2022-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invitation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Project Manager', 'project Manager'), ('Developer', 'Developer')], default='3', max_length=30),
        ),
    ]
