# Generated by Django 4.0.2 on 2022-03-04 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='project',
            name='Allow_Milestone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managingProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_color',
            field=models.CharField(blank=True, default='#6493ff', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_icon',
            field=models.CharField(blank=True, default='mdi-rocket', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_theme',
            field=models.CharField(blank=True, default='#fff #fff', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Project Management', 'Project Management'), ('Bug Tracker', 'Bug Tracker')], max_length=25),
        ),
    ]
