# Generated by Django 4.0.2 on 2022-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(),
        ),
    ]
